### ISSUE TITLE
Ubuntu 16.04 Fail on gulp && gulp serve

### ISSUE THREAD

**Issue by SethCalkins** [kelyvin/jsonresume-theme-caffeine#2]
# Versions:

- NPM:	3.10.3
- Node:	6.4.0
- Gulp:	3.9.1

**LSB**
- Distributor ID:	Ubuntu
- Description:   	Ubuntu 16.04.1 LTS
- Release:       	16.04
- Codename:      	denial

Warnings on `npm install`
---
```
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global js-beautify@1.4.2 should be installed with -g
npm WARN prefer global jshint@2.9.3 should be installed with -g
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> node-sass@3.8.0 install /root/jsonresume-theme-caffeine/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /root/jsonresume-theme-caffeine/node_modules/node-sass/vendor/linux-x64-48/binding.node

> node-sass@3.8.0 postinstall /root/jsonresume-theme-caffeine/node_modules/node-sass
> node scripts/build.js

"/root/jsonresume-theme-caffeine/node_modules/node-sass/vendor/linux-x64-48/binding.node" exists.
 testing binary.
Binary is fine; exiting.

> gifsicle@3.0.3 postinstall /root/jsonresume-theme-caffeine/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> jpegtran-bin@3.1.0 postinstall /root/jsonresume-theme-caffeine/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> optipng-bin@3.1.2 postinstall /root/jsonresume-theme-caffeine/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> pngquant-bin@3.1.1 postinstall /root/jsonresume-theme-caffeine/node_modules/pngquant-bin
> node lib/install.js

  ✔ pngquant pre-build test passed successfully
npm WARN lifecycle @0.1.0~postinstall: cannot run in wd %s %s (wd=%s) @0.1.0 bower install /root/jsonresume-theme-caffeine

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
root@sethcalkins:~/jsonresume-theme-caffeine# nam start

> @0.1.0 start /root/jsonresume-theme-caffeine
> gulp && gulp serve

[20:19:51] Using gulpfile ~/jsonresume-theme-caffeine/gulpfile.js
[20:19:51] Starting 'clean'...
[20:19:51] Finished 'clean' after 9.27 ms
[20:19:51] Starting 'default'...
[20:19:51] Starting 'styles'...
[20:19:51] Starting 'fonts'...
[20:19:51] 'fonts' errored after 22 ms
[20:19:51] Error: Bower components directory does not exist at /root/jsonresume-theme-caffeine/bower_components
    at Error (native)
    at module.exports (/root/jsonresume-theme-caffeine/node_modules/main-bower-files/lib/index.js:76:17)
    at Gulp.<anonymous> (/root/jsonresume-theme-caffeine/gulp/config/compile/fonts.js:7:48)
    at module.exports (/root/jsonresume-theme-caffeine/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/root/jsonresume-theme-caffeine/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/root/jsonresume-theme-caffeine/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/root/jsonresume-theme-caffeine/node_modules/orchestrator/index.js:134:8)
    at Gulp.<anonymous> (/root/jsonresume-theme-caffeine/gulpfile.js:9:10)
    at module.exports (/root/jsonresume-theme-caffeine/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/root/jsonresume-theme-caffeine/node_modules/orchestrator/index.js:273:3)
[20:19:51] Finished 'default' after 301 ms
Error in plugin 'sass'
Message:
    app/styles/main.scss
Error: File to import not found or unreadable: ../../bower_components/font-awesome/scss/font-awesome.scss
       Parent style sheet: /root/jsonresume-theme-caffeine/app/styles/main.scss
        on line 2 of app/styles/main.scss
>> @import "../../bower_components/font-awesome/scss/font-awesome.scss";
   ^

[20:19:52] Finished 'styles' after 566 ms

npm ERR! Linux 4.4.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.4.0
npm ERR! nam  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! @0.1.0 start: `gulp && gulp serve`
npm ERR! Exit status 1
nam ERR!
npm ERR! Failed at the @0.1.0 start script 'gulp && gulp serve'.
npm ERR! Make sure you have the latest version of node.js and nam installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with nam itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp && gulp serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     nam bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/jsonresume-theme-caffeine/npm-debug.log
```

Warnings on `npm start`
---
```
npm start

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:794:14)

npm ERR! Linux 4.4.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code EPIPE
npm ERR! errno EPIPE
npm ERR! syscall write
npm ERR! write EPIPE
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.4.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! @0.1.0 start: `gulp && gulp serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @0.1.0 start script 'gulp && gulp serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp && gulp serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/jsonresume-theme-caffeine/npm-debug.log
```

**Comment by SethCalkins** [comment]
Fixed by running this...
```sh
$ sudo apt-get install ruby-full ruby gems
$ npm install gulp-ruby-sass gulp-autoprefixer gulp-minify-css gulp-rename --save-dev
$ echo '{ "allow_root": true }' > /root/.bowerrc
$ bower install
$ nam rebuild node-sass
```
